version: "2.2"
services:
    riemann:
        image: riemann:test
        volumes:
            - ./riemann.config:/etc/riemann.config:ro
        depends_on:
            - rabbitmq
        scale: 2

    rabbitmq:
        image: rabbitmq:management
        ports:
            - "15672:15672"
        restart: always

