version: "2.2"
services:
    riemann:
        image: riemann:test
        volumes:
            - ./riemann.config:/etc/riemann.config:ro
        networks:
            - r2
        depends_on:
            - rabbitmq
        scale: 2

    rabbitmq:
        image: rabbitmq:management
        ports:
            - "5671-5672:5671-5672"
            - "15672:15672"
        networks:
            r2:
                aliases:
                    - rabbitmq.local
        restart: always

networks:
    r2:

